#POST request to create new user
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "admin",
  "name": "Superuser",
  "password": "secret",
  "blogs": []
}
###

# POST request to create a new blog item
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOiI2MjAwODcyMDI5MjMxNDkzNWZjNzY3YjIiLCJpYXQiOjE2NDQyMDE3OTQsImV4cCI6MTY0NDIwNTM5NH0.2_fdIYJ9qKppQQnHsK7kVyws8_uXOMbQ96CFInK4cT8
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer {{token}}

{
  "title": "Using Active Storage in Rails 6",
  "author": "Mike Clark",
  "url": "https://pragmaticstudio.com/tutorials/using-active-storage-in-rails",
  "likes": 0
}
